# Generated by Django 4.2.3 on 2023-08-16 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(default='', max_length=250)),
                ('tel', models.IntegerField(default='')),
                ('annEmploi', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_acad', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departement', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_niveau', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modul', models.CharField(max_length=250)),
                ('ID_Classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univers.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=250)),
                ('ID_Departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univers.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('tel', models.CharField(max_length=250)),
                ('annEntre', models.CharField(max_length=250)),
                ('ID_Annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univers.annee')),
                ('ID_Classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univers.classe')),
                ('ID_Modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univers.modul')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='ID_Filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univers.filiere'),
        ),
        migrations.AddField(
            model_name='classe',
            name='ID_niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univers.niveau'),
        ),
    ]
